package com.kneissler.util.html;

public class HTMLConst {
	public final static String DOC_START
	      = "<!DOCTYPE html>"
            +"\n<html>"
            +"\n<head>"
            +"\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            +"\n<style>"
            +"\n.collapsible {"
            +"\n  color: white;"
            +"\n  cursor: pointer;"
            +"\n  width: 100%;"
            +"\n  border: none;"
            +"\n  text-align: left;"
            +"\n  outline: none;"
            +"\n}"
            +"\n.level1 {"
            +"\n  padding: 18px;"
            +"\n  font-size: 18px;"
            +"\n}"
            +"\n.level2 {"
            +"\n  padding: 16px;"
            +"\n  font-size: 16px;"
            +"\n}"
            +"\n.level3 {"
            +"\n  padding: 14px;"
            +"\n  font-size: 14px;"
            +"\n}"
            +"\n.level4 {"
            +"\n  padding: 12px;"
            +"\n  font-size: 12px;"
            +"\n}"
            +"\n.level5 {"
            +"\n  padding: 10px;"
            +"\n  font-size: 10px;"
            +"\n}"
            +"\n.level6 {"
            +"\n  padding: 9px;"
            +"\n  font-size: 9px;"
            +"\n}"
            +"\n.normaltext {"
            +"\n  padding-right: 12px;"
            +"\n  font-size: 16px;"
            +"\n}"
            +"\n.console {"
	      +	"\n  font-family:'Courier New';"
            +"\n  padding: 10px;"
            +"\n  line-height: 125%;"
            +"\n  font-size: 14px;"
            +"\n  border: 5;"
            +"\n  background-color: black;"
            +"\n  color: white;"
            +"\n  margin-right: 24px"
            +"\n}"
            +"\n.active {"
            +"\n  color: yellow;"
            +"\n}"
            +"\n.colgreen {"
            +"\n  background-color: #009000;"
            +"\n}"
            +"\n.colgreen:hover {"
            +"\n  background-color: #00B000;"
            +"\n}"
            +"\n.colred {"
            +"\n  background-color: #A00000;"
            +"\n}"
            +"\n.colred:hover {"
            +"\n  background-color: #D00000;"
            +"\n}"
            +"\n.colblue {"
            +"\n  background-color: #0000B0;"
            +"\n}"
            +"\n.colblue:hover {"
            +"\n  background-color: #0000E0;"
            +"\n}"
            +"\n.colgray {"
            +"\n  background-color: #707070;"
            +"\n}"
            +"\n.colgray:hover {"
            +"\n  background-color: #909090;"
            +"\n}"
            +"\n.collapsible:after {"
            +"\n  content: '\\002B';"
            +"\n  color: white;"
            +"\n  font-weight: bold;"
            +"\n  float: right;"
            +"\n  margin-left: 5px;"
            +"\n}"
            +"\n"
            +"\n.active:after {"
            +"\n  content: \"\\2212\";"
            +"\n}"
            +"\n.content {"
            +"\n  padding: 0 0 0 36px;"
            +"\n  max-height: 0;"
            +"\n  overflow: hidden;"
            +"\n  background-color: #e1e1e1;"
            +"\n}"
            +"\n</style>"
            +"\n<title>";
    public final static String HTML_START 
          = "</title>\n</head>\n<body>\n";
    public final static String HTML_END 
          = "<script>"
            +"\nvar coll = document.getElementsByClassName(\"collapsible\");"
            +"\nvar i;"
            +"\nfor (i = 0; i < coll.length; i++) {"
            +"\n  coll[i].addEventListener(\"click\", function() {"
            +"\n    this.classList.toggle(\"active\");"
            +"\n    var content = this.nextElementSibling;"
            +"\n    if (content.style.maxHeight){"
            +"\n      content.style.maxHeight = null;"
            +"\n    } else {"
            +"\n      content.style.maxHeight = 1000000 + \"px\";"
            +"\n    }"
            +"\n  });"
            +"\n}"
            +"\n</script>"
            +"\n</body>"
            +"\n</html>";
    
    public final static String SECTION_HEADER_START = "<button class=\"collapsible";
    public final static String SECTION_HEADER_MIDDLE = "\">";
    public final static String SECTION_HEADER_END = "</button>";
    public final static String SECTION_CONTENT_START = "<div class=\"content\">";
    public final static String SECTION_CONTENT_END = "</div>";
    public final static String PARAGRAPH_START = "<p class=\"normaltext\">";
    public final static String PARAGRAPH_END = "</p>";
    public final static String CONSOLE_START = "<div class=\"console\">";
    public final static String CONSOLE_END = "</div><br>";
    public final static String HEADER_START = "<h1>";
    public final static String HEADER_END = "</h1>";
    

}
